# set up as `.gitlab-ci.yml` file in the root of your application repo directory.

# https://docs.gitlab.com/ee/ci/yaml/README.html#workflowrules-templates
# Only runs if a merge request or the master branch

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test:runtest

variables:
  TESTSTATE: "not run"
  SN_AUTH_DEV: $(K8S_SECRET_SN_AUTH_DEV)
  DOTENV_FILE: "$CI_PROJECT_DIR/build.env"
  DEV_ENV: "dev90628.service-now.com"
  SYSID: "acc795ef1b442110fef77596cc4bcbf3"
  TESTSUITEID: "ab72ec6b8f033300a8616c7827bdee01"

image: servicenowdevx/sncicd-gitlab-docker:latest

RunTest:
  stage: test:runtest
  variables:
    task: TestRun
    NOWINSTANCE: $DEV_ENV
    NOWAUTH: $SN_AUTH_DEV
    TEST_SUITE_SYS_ID: $TESTSUITEID
  artifacts:
    reports:
      dotenv: $DOTENV_FILE
  script:
    - echo 'TESTSTATE=started' >> $DOTENV_FILE
    - task.sh
  except:
    - main

