# set up as `.gitlab-ci.yml` file in the root of your application repo directory.

# https://docs.gitlab.com/ee/ci/yaml/README.html#workflowrules-templates
# Only runs if a merge request or the master branch

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build:applychanges
  - build:publishapp
  - test:runtest

variables:
  TESTSTATE: "not run"
  SN_AUTH_DEV: $(K8S_SECRET_SN_AUTH_DEV)
  DOTENV_FILE: "$CI_PROJECT_DIR/build.env"
  DEV_ENV: "dev90628.service-now.com"
  SYSID: "acc795ef1b442110fef77596cc4bcbf3"
  TESTSUITEID: "c5aba1e31bc42110fef77596cc4bcbb1"

image: servicenowdevx/sncicd-gitlab-docker:latest

ApplyRemoteChanges:
  stage: build:applychanges
  variables:
    task: SCApply
    NOWINSTANCE: $DEV_ENV
    NOWAUTH: $SN_AUTH_DEV
    APP_SYS_ID: $SYSID
  script:
    - export
    - task.sh
  except:
    - main

AppPublish:
  stage: build:publishapp
  variables:
    task: AppPublish
    NOWINSTANCE: $DEV_ENV
    NOWAUTH: $SN_AUTH_DEV
    SYS_ID: $SYSID
    # autodetect|detect|exact|template
    # autodetect - detect app version via REST call. Table depends on IS_APP_CUSTOMIZATION param.
    # detect     - detect app version via file(sys_app_<id>.xml|sys_app_customization_<id>.xml).
    #              Filename depends on IS_APP_CUSTOMIZATION param.
    # template   - in x.y.z format you should define x.y part, z would be autogenerated based on build num.
    # exact      - define exact version of app(e.g. 1.2.3).
    VERSIONFORMAT: "autodetect" 
    DEVNOTES: "Updated version"
    # If true, requires SYS_ID instead of SCOPE. true|false
    IS_APP_CUSTOMIZATION: "true" 
  artifacts:
    reports:
      dotenv: $DOTENV_FILE
  script:
    - task.sh
  except:
    - main

RunTest:
  stage: test:runtest
  variables:
    task: TestRun
    NOWINSTANCE: $DEV_ENV
    NOWAUTH: $SN_AUTH_DEV
    TEST_SUITE_SYS_ID: $TESTSUITEID
  artifacts:
    reports:
      dotenv: $DOTENV_FILE
  script:
    - echo 'TESTSTATE=started' >> $DOTENV_FILE
    - task.sh
  except:
    - main

